# Generated by Django 5.2.11 on 2026-02-11 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('lectures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analytics.curriculum'),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_items', to='lectures.lecture'),
        ),
        migrations.AddField(
            model_name='reroutinglog',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rerouting_logs', to='analytics.curriculum'),
        ),
    ]
