# Generated by Django 5.2.11 on 2026-02-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='retention_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Dropout risk analysis data'),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='learning_status',
            field=models.JSONField(blank=True, default=dict, help_text='Micro-tracking of watch history and checkpoints'),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='reflection_data',
            field=models.JSONField(blank=True, default=dict, help_text='User reflections and AI feedback'),
        ),
    ]
