# Generated by Django 5.2.11 on 2026-02-11 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_tutor', '0001_initial'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='lecture',
            field=models.ForeignKey(help_text='Context for the chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='lectures.lecture'),
        ),
    ]
