# Generated by Django 5.2.11 on 2026-02-11 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_tutor', '0002_initial'),
        ('lectures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_tutor.aichatsession'),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='lecture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='lectures.lecture'),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for default AI note, set for user custom note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
