# Generated by Django 5.2.11 on 2026-02-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cohort_analytics',
            field=models.JSONField(blank=True, default=dict, help_text='Cached average stats for the course cohort'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='ai_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='lecture',
            name='checkpoints',
            field=models.JSONField(blank=True, default=list, help_text='List of checkpoints/quizzes'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='script_segments',
            field=models.JSONField(blank=True, default=list, help_text='List of script segments for pinpoint search'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='supplemental_materials',
            field=models.JSONField(blank=True, default=list, help_text='Conditional supplemental materials'),
        ),
    ]
