# Generated by Django 5.2.11 on 2026-02-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_course_cohort_analytics_lecture_ai_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
