# Generated by Django 5.2.11 on 2026-02-11 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('TECH_LEAD', 'Tech Lead'), ('HR', 'HR Manager'), ('VC', 'VC Investor'), ('PEER', 'Peer Developer'), ('CUSTOMER', 'Potential Customer'), ('CTO', 'CTO')], max_length=20)),
                ('system_prompt', models.TextField(help_text='Prompt for AI Persona')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('NORMAL', 'Normal'), ('HARD', 'Hard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_question_count', models.IntegerField(default=5, help_text='Target questions for auto-termination')),
                ('time_limit_seconds', models.IntegerField(default=600, help_text='Time limit in seconds')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TIMEOUT', 'Timeout')], default='IN_PROGRESS', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback_summary', models.TextField(blank=True)),
                ('evaluation_detail', models.JSONField(blank=True, default=dict, help_text='Detailed evaluation results')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='career.interviewpersona')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='assets.portfolio')),
            ],
        ),
    ]
